[MWPW-139950] Virtual Comments extension - final fixes and initial commit
adobecom/virtual-comments pull request #2
Opened 2023-12-20 04:36 UTC by drashti1712

2024-01-08 05:35 UTC, amitbikram commented
All the save and fetch operation should be abstracted away and moved to a different file/module.

2024-01-08 05:35 UTC, amitbikram requested changes

2024-01-08 05:35 UTC, amitbikram commented on package.json
> +	"license": "MIT",
Project license is file is Apache and we have mentioned here MIT. Please correct it.

2024-01-08 05:35 UTC, amitbikram commented on src/webView/htmlContent.ts
> +    return `
Templates should be moved to separate file

2024-01-31 07:00 UTC, amitbikram approved these changes

2024-01-31 15:10 UTC, aishwaryamathuria approved these changes

2024-02-05 05:03 UTC, merged